# Generated by Django 5.1.3 on 2025-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_expense', '0002_rename_group_expensegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
